
name = "crazy-art"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "crazyart-db"
database_id = "f0a05c7b-af49-449a-a9d7-280e94e15865" # SUBSTITUA PELO ID REAL ENCONTRADO NO DASHBOARD
